### ISSUE TITLE
Max connection to one AP is 4

### ISSUE THREAD

**Issue by tinamore** [imerso/ESPForwarder#3]
Hi

Max client connect to AP esp8266 is 4 station.

How to "It can handle up to 254 connected devices" ?

Thanks

**Comment by imerso** [comment]
It can handle up to 254 connected devices, although the limit is currently set to only 5 in the code ahead. You can change that limit easily just by setting the amount on the MAX_SLOTS define.


This info is in the readme file, did you change that hard-coded limit already?

**Comment by tinamore** [comment]
I known can setting the amount on the MAX_SLOTS define.

BUT "The maximum station connections in softAP is 4"

http://bbs.espressif.com/viewtopic.php?t=1155

one AP can not get connected more than 4 station.

**Comment by imerso** [comment]
Yes, it seems you're right, so for more than 4 you need a custom firmware.

I did not test it in practice as I would not expect such a low limit, I can guarantee that the code itself is able to forward up to 254 devices, I did not know though that the ap was hard-coded to a maximum of only 4 connections, sorry.

**Comment by tinamore** [comment]
I think: ESP is a limited device, If more station connect to the AP, the AP will ESP ESP 1 not stable.
Project of you gives me inspiration and idea of a connection between the esp.
Thanks.
